insert into competitors (id, company_name, website, category, positioning, services_offered, target_customers, strengths, weaknesses, notes, tags)
values
('00000000-0000-0000-0000-000000000101', 'Intercoastal Consulting & Life Care Planning', 'https://www.iclcp.com/', 'Life Care Planning', 'Life care planning and expert witness service provider for plaintiff and defense attorneys.', 'Life care plans, life care plan critiques and rebuttals, expert witness testimony, standards of care consultations', 'Plaintiff attorneys and defense attorneys handling catastrophic and non-catastrophic injury cases', 'Certified life care planning expertise, explicit rebuttal service line, attorney-focused expert witness positioning', 'Public positioning appears narrower than PLCP damages valuation breadth across earnings and household services', 'Public website emphasizes certified experts and litigation support for attorneys.', array['life-care-planning','expert-witness','rebuttal-review']),
('00000000-0000-0000-0000-000000000102', 'Turning Point Life Care Planning', 'https://tplcp.com/', 'Life Care Planning', 'Life care planning experts serving individuals and legal professionals throughout North America.', 'Life care planning, expert witness life care planning, medical cost projections, rebuttals, functional assessments', 'Attorneys and clients throughout the United States and North America', '20+ years of life care planning experience, thousands of life care plans prepared, defensible court-oriented methodology', 'Public site emphasizes planner methodology rather than physician-led damages valuation breadth', 'Public messaging highlights traumatic brain injury, spinal cord injury, orthopedic trauma, and complex medical conditions.', array['life-care-planning','expert-witness','north-america']),
('00000000-0000-0000-0000-000000000103', 'Case In Point', 'https://www.ciplcp.com/', 'Life Care Planning and Litigation Support', 'Florida-based life care planning and litigation support firm with nationwide team members.', 'Life care planning, future plans of care, expert witness services, physician consultations and review, vocational expert services, testimony, medical records review, research', 'Law firms working on medical malpractice, product liability, personal injury, pediatric and adult cases', 'More than 50 years of collective experience, multidisciplinary team, vocational and physician consultation breadth', 'Public positioning is broad but less explicitly physician-led than PLCP''s public positioning', 'Public site says the firm is woman-owned and woman-run and supports plaintiff and defense matters.', array['life-care-planning','vocational','litigation-support']),
('00000000-0000-0000-0000-000000000104', 'LifeCare Collaborative', 'https://www.lifecarecol.com/', 'Life Care Planning', 'Houston-based nationwide life care planning provider focused on medical needs, costs, and economic loss valuation.', 'Life care planning, projection of medical needs and associated costs, economic damage analysis, economic loss valuation, medical malpractice expert witness, litigation support', 'Attorneys handling catastrophic injury, chronic illness, and medical malpractice matters', 'Nationwide service, transdisciplinary healthcare team, explicit economic loss valuation messaging', 'Publicly available positioning appears less focused on large physician expert network scale than PLCP', 'Public site emphasizes objective basis for economic loss valuation for attorneys.', array['life-care-planning','economic-damages','houston']),
('00000000-0000-0000-0000-000000000105', 'Certified Life Care Planning Doctors', 'https://clcpdoctors.com/', 'Physician Life Care Planning', 'Physician-led life care planning, expert witness, and independent medical examination provider.', 'Life care planning, expert witness testimony, consulting, litigation support, independent medical examinations', 'Legal clients needing medical expertise for severe injury or illness damages valuation', 'Physician-led positioning, CLCP credentialing, IME service adjacency', 'Public profile appears centered around an individual named expert rather than PLCP''s broader national expert network', 'Public site features Dr. Adam Locketz and emphasizes medical expertise for legal cases.', array['physician-led','life-care-planning','ime']),
('00000000-0000-0000-0000-000000000106', 'American Life Care Planning', 'https://americanlifecareplanning.com/services/', 'Life Care Planning and Vocational Services', 'Attorney-focused expert services for catastrophic injury damages, life care plans, future medical cost projections, and vocational evaluation.', 'Life care plans, future medical cost projections, expert witness services, vocational testing, earning capacity evaluation, disability management testimony', 'Attorneys documenting damages in catastrophic injury cases', 'Practicing board-certified neurosurgeon expert witness positioning, vocational evaluation breadth', 'Public site provides less evidence of PLCP-like process scale, turnaround claims, or fixed-price positioning', 'Public service page highlights practicing Board Certified Neurosurgeons who are Certified Life Care Planners and Certified Nurse Life Care Planners.', array['life-care-planning','vocational','neurosurgeon'])
on conflict (id) do update set
company_name = excluded.company_name,
website = excluded.website,
category = excluded.category,
positioning = excluded.positioning,
services_offered = excluded.services_offered,
target_customers = excluded.target_customers,
strengths = excluded.strengths,
weaknesses = excluded.weaknesses,
notes = excluded.notes,
tags = excluded.tags,
updated_at = now();

insert into intelligence_items (id, title, source_url, source_type, publication_date, author, raw_content, tags, competitor_id)
values
('00000000-0000-0000-0000-000000000301', 'Intercoastal Consulting positions around rebuttals and expert witness support', 'https://www.iclcp.com/', 'webpage', '2026-04-20', 'Intercoastal Consulting & Life Care Planning', 'Intercoastal Consulting & Life Care Planning publicly describes services for plaintiff and defense attorneys including life care plans, life care plan critiques and rebuttals, expert witness testimony, and standards of care consultations.', array['rebuttal-review','expert-witness','attorneys'], '00000000-0000-0000-0000-000000000101'),
('00000000-0000-0000-0000-000000000302', 'Turning Point emphasizes court-defensible plans and 20+ years of experience', 'https://tplcp.com/', 'webpage', '2026-04-22', 'Turning Point Life Care Planning', 'Turning Point Life Care Planning says attorneys choose the firm for sound methodology, insight, experience, and integrity. The public site cites Certified Life Care Planners with clinical rehabilitation backgrounds, evidence-based life care plans and rebuttals, 20+ years of experience, thousands of life care plans prepared, and expert witness services.', array['defensibility','experience','expert-witness'], '00000000-0000-0000-0000-000000000102'),
('00000000-0000-0000-0000-000000000303', 'Case In Point combines life care planning, vocational services, and physician consultation', 'https://www.ciplcp.com/', 'webpage', '2026-04-28', 'Case In Point', 'Case In Point publicly describes a Florida-based business with team members nationwide, more than 50 years of collective experience, and services including life care planning, future plans of care, expert witness services, physician consultation and review, vocational expert services, testimony, medical records review, and research.', array['vocational','physician-consultation','litigation-support'], '00000000-0000-0000-0000-000000000103'),
('00000000-0000-0000-0000-000000000304', 'LifeCare Collaborative promotes nationwide economic damages and litigation support', 'https://www.lifecarecol.com/', 'webpage', '2026-05-01', 'LifeCare Collaborative', 'LifeCare Collaborative describes nationwide life care planning, projection of medical needs and associated costs, economic damage analysis, economic loss valuation, medical malpractice expert witness, and litigation support services. Its public site says its plans provide attorneys an objective basis for economic loss valuation.', array['economic-damages','litigation-support','nationwide'], '00000000-0000-0000-0000-000000000104'),
('00000000-0000-0000-0000-000000000305', 'Certified Life Care Planning Doctors uses physician-led expert and IME positioning', 'https://clcpdoctors.com/', 'webpage', '2026-05-03', 'Certified Life Care Planning Doctors', 'Certified Life Care Planning Doctors publicly offers life care planning, expert witness testimony and consulting, litigation support, and independent medical examinations. The site highlights Dr. Adam Locketz as an MD, DABPMR, XDEA, and CLCP.', array['physician-led','ime','expert-witness'], '00000000-0000-0000-0000-000000000105'),
('00000000-0000-0000-0000-000000000306', 'American Life Care Planning combines medical and vocational damages services', 'https://americanlifecareplanning.com/services/', 'webpage', '2026-05-05', 'American Life Care Planning', 'American Life Care Planning publicly states that it works with attorneys to document damages in catastrophic injury cases. Services include life care plans, future medical cost projections, expert witness services by practicing Board Certified Neurosurgeons who are Certified Life Care Planners, Certified Nurse Life Care Planners, vocational testing, earning capacity analysis, and disability management testimony.', array['vocational','medical-cost-projections','neurosurgeon'], '00000000-0000-0000-0000-000000000106')
on conflict (id) do update set
title = excluded.title,
source_url = excluded.source_url,
source_type = excluded.source_type,
publication_date = excluded.publication_date,
author = excluded.author,
raw_content = excluded.raw_content,
tags = excluded.tags,
competitor_id = excluded.competitor_id;

insert into plcp_profile (id, core_services, differentiators, pricing_position, operational_strengths, weaknesses, target_customer_profile, strategic_goals)
values (
'00000000-0000-0000-0000-000000000201',
array['Life Care Plans','Medical Cost Assessments','Present Value Assessments','Loss of Earnings Capacity Assessments','Present Value Loss of Earnings Assessments','Present Value Loss of Household Services Assessments'],
array['Board Certified Physician Life Care Planners','Practicing physicians specializing in Physical Medicine and Rehabilitation','Full range of life care planning and damages valuation services from a single provider','Standard six-week turnaround with expedited services available','Transparent fixed pricing','Over 90 Board Certified Life Care Planning Physicians and Damages Valuation Experts','ClearView Process designed for quality, value, efficiency, and convenience'],
'Public website positions pricing as transparent, affordable, and fixed, with efficiency from systems and workflow processes.',
array['Nationwide provider headquartered in San Antonio, Texas','Large expert network covering physician life care planners and forensic professionals','Streamlined systems and workflow processes','Case management support for clients','Complimentary continuing legal education for plaintiff and defense counsel'],
array['No public self-disclosed weaknesses found; replace with internal assessment','Public profile emphasizes strengths, so competitive risks should be validated with customer feedback and win/loss data'],
'Attorneys for plaintiff and defense, government agencies, insurance companies, trusts, courts, legal professionals, insurance and claims professionals handling chronically and catastrophically ill or injured individuals.',
array['Public mission: be the world''s highest quality provider of damages valuation services','Support clients defining future medical care, loss of earnings capacity, and loss of household services','Maintain differentiation around expertise, speed, range, convenience, affordability, and scale','Internal strategic goals are not publicly disclosed and should be added by admins']
)
on conflict (id) do update set
core_services = excluded.core_services,
differentiators = excluded.differentiators,
pricing_position = excluded.pricing_position,
operational_strengths = excluded.operational_strengths,
weaknesses = excluded.weaknesses,
target_customer_profile = excluded.target_customer_profile,
strategic_goals = excluded.strategic_goals,
updated_at = now();
